### GET ALL BOOKS
GET http://localhost:3000/books

### GET CURRENT BOOK
GET http://localhost:3000/books/review

### GET ALL BOOKS ADDED BY USER
GET http://localhost:3000/books/user

### GET BOOK BY ID
GET http://localhost:3000/books/7

### ADD NEW BOOK
POST http://localhost:3000/books
Content-Type: application/json

{
    "title": "Goals",
    "author": "Brian Tracy"
}

### UPDATE BOOK
PATCH http://localhost:3000/books/update/5
Content-Type: application/json

{
    "title": "No Excuses"
}

### DELETE BOOK BY ID
DELETE http://localhost:3000/books/delete/7
Content-Type: application/json
